/// @description Insert description here
// You can write your code in this editor




deadzone = winControl.globalDeadzone;
iCounter = 0;
random_set_seed(randomise());
surf = -1;

//set at least three blocks on each side to be power ups

if(type != 3){
choice = irandom_range(0,99);

	if(choice < 70){
	
		type = 0;
		
	} else if(choice < 97){
	
		type = 1;
		
	} else type = 2;





	if(type == 1){
	
	
		hp = 10;	
		sprite_index = stoneSprite;
	
	}

	if(type == 2){
	
		hp = 15;	
		//sprite_index = powerSprite; // these are hidden power up blocks not generated by the procedure
		
	}


} else {
	image_xscale = 15;
	image_yscale = 10;
	hp = 2000;
}


maxpads = gamepad_get_device_count();


function turnSpecial(){
	
		type = 2;
		hp = 15;
		sprite_index = powerSprite;
	
}

function noBlock(){
	
	if(destroyMe && type != 2) instance_destroy();	
	
}